import { Box, Container, Flex, Link } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import NextLink from "next/link";
import { FC, useContext } from "react";
import { UserContext } from "../components/providers/UserProvider";

const DashboardItem: FC = ({ children }) => {
    return (
        <Box
            mx={"5"}
            padding={"3"}
            border={"1px"}
            borderColor={"whiteAlpha.50"}
            borderRadius="sm"
            background={"whitesmoke"}
            width={"48"}
            height={"55"}
            _hover={{ borderColor: "teal.200" }}>
            {children}
        </Box>
    );
};

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container maxW={"container.xl"} my="5">
                <Flex>
                    <DashboardItem>
                        <NextLink href="/pelanggan" passHref>
                            <Link>Pelanggan</Link>
                        </NextLink>
                    </DashboardItem>
                    <DashboardItem>
                        <NextLink href="/petugas" passHref>
                            <Link>Petugas</Link>
                        </NextLink>
                    </DashboardItem>
                    <DashboardItem>
                        <NextLink href="/pembayaran" passHref>
                            <Link>Pembayaran</Link>
                        </NextLink>
                    </DashboardItem>
                </Flex>
            </Container>
        </>
    );
};

export default Home;
